{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ include "mediawiki-backup.fullname" . }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "mediawiki-backup.fullname" . }}'
subjects:
  - kind: ServiceAccount
    name: '{{ include "mediawiki-backup.serviceAccountName" . }}'
    namespace: '{{ .Release.Namespace }}'
{{- end }}