name: Publish new container

on:
  push:
    branches:
      # - main
      - workflows-test
    tags: 
      - "*"

jobs:
  container:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/fernferret/mediawiki-backup:${{ github.ref_name }}