name: Publish new container

on:
  push:
    branches:
      - main
    tags: 
      - "*"

jobs:
  container:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - uses: sigstore/cosign-installer@main

      - name: Write signing key to disk (only needed for `cosign sign --key`)
        run: echo "${{ secrets.SIGNING_SECRET }}" > cosign.key

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/fernferret/mediawiki-backup:${{ github.ref_name }}

      - name: Sign container image
        run: |
          cosign sign --key cosign.key \
            ghcr.io/fernferret/mediawiki-backup:${{ github.ref_name }}
